In [2]:
import dart_fss as dart
import pandas as pd
import os
from dotenv import load_dotenv

# set up api keys from env
load_dotenv()
api_key = os.getenv("DART_API_KEY")
dart.set_api_key(api_key=api_key)

# fetch corp codes data and create dataframe
all_corps = dart.api.filings.get_corp_code()
all_corps_df = pd.DataFrame(all_corps)

all_corps_df

Error occurred during getting browser(s): random, but was suppressed with fallback.

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,00434003,다코,Daco corporation,None,20170630
1,00430964,굿앤엘에스,"Good & LS Co.,Ltd.",None,20170630
2,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,None,20170630
3,00179984,연방건설산업,youn bao,None,20170630
4,00420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",None,20170630
...,...,...,...,...,...
113357,01913127,디지탈테크,"digitalltek co.,ltd.",None,20250423
113358,01913491,피유란,"PYURAN Co., Ltd.",None,20250423
113359,01947212,하나모터제일차,Hana Mortor 1st Corp.,None,20250820
113360,00579342,영광,"YOUNGKWANG Co., Ltd",None,20250820
113361,01271410,어뮤즈코리아,Amuse Corporation,None,20250820

In [6]:
# save it to excel  (if no directory exists, create it)
if not os.path.exists('data'):
    os.makedirs('data')
all_corps_df.to_excel(f"data/corp_list.xlsx", index=False)